import pg from "pg";

const { Client } = pg;
const JSON_HEADERS = { "cache-control": "no-store", "content-type": "application/json; charset=utf-8" };
const CORS_HEADERS = { "access-control-allow-origin": "*", "access-control-allow-methods": "GET,POST,OPTIONS", "access-control-allow-headers": "content-type,x-kc-client", "access-control-max-age": "86400" };
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...CORS_HEADERS}})}
async function checkSupabase(env){const t=Date.now();try{const r=await fetch(`${env.SUPABASE_URL}/auth/v1/health`,{headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY},cf:{cacheTtl:0}});return{reachable:r.ok,statusCode:r.status,latencyMs:Date.now()-t}}catch(e){return{reachable:false,statusCode:null,latencyMs:Date.now()-t,error:e instanceof Error?e.message:"Unknown Supabase error"}}}
async function withNeon(env,fn){const c=new Client({connectionString:env.HYPERDRIVE.connectionString});try{await c.connect();return await fn(c)}finally{try{await c.end()}catch{}}}
async function checkNeon(env){const t=Date.now();if(!env.HYPERDRIVE?.connectionString)return{reachable:false,latencyMs:Date.now()-t,error:"Hyperdrive binding missing"};try{await withNeon(env,c=>c.query("SELECT 1 AS ok"));return{reachable:true,latencyMs:Date.now()-t}}catch(e){return{reachable:false,latencyMs:Date.now()-t,error:e instanceof Error?e.message:"Unknown Neon error"}}}
async function runFallbackReadWriteProbe(env){const marker=crypto.randomUUID(),t=Date.now();try{const ok=await withNeon(env,async c=>{await c.query("BEGIN");try{await c.query("CREATE TEMP TABLE kc_failover_probe (marker text NOT NULL) ON COMMIT DROP");await c.query("INSERT INTO kc_failover_probe(marker) VALUES($1)",[marker]);const r=await c.query("SELECT marker FROM kc_failover_probe LIMIT 1");await c.query("ROLLBACK");return r.rows[0]?.marker===marker}catch(e){await c.query("ROLLBACK");throw e}});return{readWrite:ok===true,latencyMs:Date.now()-t,persistentChanges:false}}catch(e){return{readWrite:false,latencyMs:Date.now()-t,persistentChanges:false,error:e instanceof Error?e.message:"Unknown failover probe error"}}}
function chooseBackend(p,f){return p?"SUPABASE":f?"NEON":"LOCAL_QUEUE"}
function cleanTransaction(row){if(!row||typeof row!=="object")throw new Error("INVALID_TRANSACTION");const transactionId=String(row.transactionId||"").trim(),registerId=String(row.registerId||"").trim();if(!transactionId||transactionId.length>160)throw new Error("INVALID_TRANSACTION_ID");if(!registerId||registerId.length>100)throw new Error("INVALID_REGISTER_ID");const payload=JSON.stringify(row);if(payload.length>180000)throw new Error("TRANSACTION_TOO_LARGE");return{transactionId,registerId,registerName:String(row.registerName||"").slice(0,160)||null,occurredAt:row.endTime||row.time||row.startTime||null,recordHash:row.recordHash?String(row.recordHash).slice(0,256):null,payload:row}}
async function saveTransactions(env,inputRows){if(!Array.isArray(inputRows)||inputRows.length<1||inputRows.length>100)throw new Error("INVALID_BATCH_SIZE");const rows=inputRows.map(cleanTransaction);return withNeon(env,async c=>{await c.query("BEGIN");const results=[];try{for(const row of rows){const ins=await c.query(`INSERT INTO public.kc_failover_transactions (transaction_id,register_id,register_name,occurred_at,record_hash,payload) VALUES ($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT (transaction_id) DO NOTHING RETURNING transaction_id`,[row.transactionId,row.registerId,row.registerName,row.occurredAt,row.recordHash,JSON.stringify(row.payload)]);if(ins.rowCount===1){results.push({transactionId:row.transactionId,status:"STORED"});continue}const ex=await c.query("SELECT record_hash,payload FROM public.kc_failover_transactions WHERE transaction_id=$1",[row.transactionId]);const old=ex.rows[0],sameHash=Boolean(row.recordHash&&old?.record_hash&&row.recordHash===old.record_hash),samePayload=JSON.stringify(old?.payload??null)===JSON.stringify(row.payload);results.push({transactionId:row.transactionId,status:(!sameHash&&!samePayload)?"CONFLICT":"ALREADY_STORED"})}await c.query("COMMIT");return results}catch(e){await c.query("ROLLBACK");throw e}})}
async function restoreTransactions(env,registerId,since){if(!registerId||registerId.length>100)throw new Error("INVALID_REGISTER_ID");return withNeon(env,async c=>{const p=[registerId];let w="register_id=$1";if(since){p.push(since);w+=" AND occurred_at >= $2::timestamptz"}const r=await c.query(`SELECT payload FROM public.kc_failover_transactions WHERE ${w} ORDER BY occurred_at NULLS LAST,received_at LIMIT 5000`,p);return r.rows.map(x=>x.payload)})}
async function reconcileTransactions(env,registerId,ids){if(!registerId||registerId.length>100)throw new Error("INVALID_REGISTER_ID");if(!Array.isArray(ids)||ids.length>5000)throw new Error("INVALID_ID_LIST");const localIds=[...new Set(ids.map(String).filter(Boolean))];return withNeon(env,async c=>{const r=await c.query("SELECT transaction_id FROM public.kc_failover_transactions WHERE register_id=$1",[registerId]),remote=new Set(r.rows.map(x=>x.transaction_id)),local=new Set(localIds);return{missingRemote:localIds.filter(id=>!remote.has(id)),missingLocal:[...remote].filter(id=>!local.has(id)),remoteCount:remote.size,localCount:local.size}})}
async function deleteTestTransaction(env,id){return withNeon(env,c=>c.query("DELETE FROM public.kc_failover_transactions WHERE transaction_id=$1",[id]))}
async function scenario1(env){const a=await checkSupabase(env),f=await runFallbackReadWriteProbe(env),b=await checkSupabase(env),pass=a.reachable&&f.readWrite&&b.reachable;return{id:1,name:"Supabase down -> Neon -> Supabase recovery",status:pass?"PASS":"FAIL",before:a,simulatedOutage:{primaryForcedDown:true,activeBackend:"NEON",fallback:f},recovery:{primary:b,activeBackend:b.reachable?"SUPABASE":"NEON"},safeSimulation:true}}
async function scenario2(env){const p=await checkSupabase(env),f=await checkNeon(env),activeBackend=chooseBackend(p.reachable,false);return{id:2,name:"Neon down while Supabase remains healthy",status:p.reachable&&activeBackend==="SUPABASE"?"PASS":"FAIL",primary:p,fallbackBeforeSimulation:f,simulatedFallbackDown:true,activeBackend,safeSimulation:true}}
async function scenario3(env){const p=await checkSupabase(env),f=await checkNeon(env),activeBackend=chooseBackend(false,false);return{id:3,name:"Both DBs down -> local queue required",status:activeBackend==="LOCAL_QUEUE"?"PASS":"FAIL",primaryBeforeSimulation:p,fallbackBeforeSimulation:f,simulatedPrimaryDown:true,simulatedFallbackDown:true,activeBackend,localQueueRequired:true,clientQueueVerified:false,safeSimulation:true}}
async function scenario4(env){const p=await checkSupabase(env),f=await checkNeon(env),queued=["q1","q2","q3"],activeDuringOutage=chooseBackend(false,false),activeAfterRecovery=chooseBackend(p.reachable,f.reachable),pass=activeDuringOutage==="LOCAL_QUEUE"&&queued.length===3&&activeAfterRecovery!=="LOCAL_QUEUE";return{id:4,name:"Local queue -> backend recovery -> replay readiness",status:pass?"PASS":"FAIL",queuedTransactions:queued.length,activeDuringOutage,primaryAfter:p,fallbackAfter:f,activeAfterRecovery,replayRequired:true,note:"Gateway verifies recovery/replay readiness; browser IndexedDB queue itself must be integration-tested in client.",safeSimulation:true}}
async function scenario5(env){const id=`supergau-${crypto.randomUUID()}`,row={transactionId:id,registerId:"SUPERGAU_TEST",registerName:"SAFE_TEST",time:new Date().toISOString(),recordHash:`hash-${id}`,test:true};try{const first=await saveTransactions(env,[row]),second=await saveTransactions(env,[row]),restored=await restoreTransactions(env,"SUPERGAU_TEST",null),matches=restored.filter(x=>x.transactionId===id);const pass=first[0]?.status==="STORED"&&second[0]?.status==="ALREADY_STORED"&&matches.length===1;return{id:5,name:"Replay idempotency -> no duplicate transaction",status:pass?"PASS":"FAIL",first:first[0],replay:second[0],storedCopies:matches.length,safeSimulation:true}}finally{try{await deleteTestTransaction(env,id)}catch{}}}
async function scenario6(env){const id=`supergau-${crypto.randomUUID()}`,base={transactionId:id,registerId:"SUPERGAU_TEST",time:new Date().toISOString(),recordHash:`hash-a-${id}`,amount:1,test:true},changed={...base,recordHash:`hash-b-${id}`,amount:2};try{const first=await saveTransactions(env,[base]),second=await saveTransactions(env,[changed]);const pass=first[0]?.status==="STORED"&&second[0]?.status==="CONFLICT";return{id:6,name:"Conflicting replay -> conflict detected, original protected",status:pass?"PASS":"FAIL",first:first[0],conflictingReplay:second[0],safeSimulation:true}}finally{try{await deleteTestTransaction(env,id)}catch{}}}
async function scenario7(env){const run=crypto.randomUUID(),registerId=`SUPERGAU_ATOMIC_${run.slice(0,8)}`,goodId=`supergau-atomic-good-${run}`,good={transactionId:goodId,registerId,time:new Date().toISOString(),recordHash:`hash-${goodId}`,test:true},bad={...good,transactionId:""};let rejected=false,error=null;try{await saveTransactions(env,[good,bad])}catch(e){error=e instanceof Error?e.message:String(e);rejected=error==="INVALID_TRANSACTION_ID"}const restored=await restoreTransactions(env,registerId,null),pass=rejected&&restored.length===0;return{id:7,name:"Atomic validation -> invalid mixed batch stores nothing",status:pass?"PASS":"FAIL",rejected,error,storedAfterReject:restored.length,safeSimulation:true}}
async function scenario8(env){const run=crypto.randomUUID(),registerId=`SUPERGAU_LIMIT_${run.slice(0,8)}`,rows=Array.from({length:101},(_,i)=>({transactionId:`supergau-limit-${run}-${i}`,registerId,time:new Date(Date.now()+i).toISOString(),recordHash:`hash-${run}-${i}`,test:true}));let rejected=false,error=null;try{await saveTransactions(env,rows)}catch(e){error=e instanceof Error?e.message:String(e);rejected=error==="INVALID_BATCH_SIZE"}const restored=await restoreTransactions(env,registerId,null),pass=rejected&&restored.length===0;return{id:8,name:"Batch limit -> 101 rows rejected without partial write",status:pass?"PASS":"FAIL",rejected,error,storedAfterReject:restored.length,safeSimulation:true}}
async function scenario9(env){const run=crypto.randomUUID(),registerId=`SUPERGAU_SINCE_${run.slice(0,8)}`,base=Date.now(),rows=[0,1000,2000].map((d,i)=>({transactionId:`supergau-since-${run}-${i+1}`,registerId,time:new Date(base+d).toISOString(),recordHash:`hash-${run}-${i+1}`,sequence:i+1,test:true}));try{const stored=await saveTransactions(env,rows),all=await restoreTransactions(env,registerId,null),since=await restoreTransactions(env,registerId,rows[1].time),ids=since.map(x=>x.transactionId),expected=[rows[1].transactionId,rows[2].transactionId],pass=stored.every(x=>x.status==="STORED")&&all.length===3&&ids.length===2&&ids[0]===expected[0]&&ids[1]===expected[1];return{id:9,name:"Incremental restore -> since filter returns exact ordered suffix",status:pass?"PASS":"FAIL",storedCount:stored.length,fullRestoreCount:all.length,since:rows[1].time,incrementalIds:ids,expectedIds:expected,safeSimulation:true}}finally{for(const row of rows){try{await deleteTestTransaction(env,row.transactionId)}catch{}}}}
const scenarios=[scenario1,scenario2,scenario3,scenario4,scenario5,scenario6,scenario7,scenario8,scenario9];
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:CORS_HEADERS});const url=new URL(request.url),path=url.pathname;try{if(path==="/sync/transaction"&&request.method==="POST"){const b=await request.json(),r=await saveTransactions(env,[b.transaction]),conflict=r.some(x=>x.status==="CONFLICT");return json({status:conflict?"CONFLICT":"OK",results:r},conflict?409:200)}if(path==="/sync/batch"&&request.method==="POST"){const b=await request.json(),r=await saveTransactions(env,b.transactions),conflicts=r.filter(x=>x.status==="CONFLICT");return json({status:conflicts.length?"PARTIAL":"OK",results:r,conflicts},conflicts.length?207:200)}if(path==="/sync/transactions"&&request.method==="GET"){const registerId=url.searchParams.get("register_id")||"",since=url.searchParams.get("since")||null,t=await restoreTransactions(env,registerId,since);return json({status:"OK",registerId,count:t.length,transactions:t})}if(path==="/sync/reconcile"&&request.method==="POST"){const b=await request.json(),r=await reconcileTransactions(env,String(b.registerId||""),b.transactionIds||[]);return json({status:"OK",...r})}if(path==="/supergau")return json(await scenario1(env));const m=path.match(/^\/scenario\/(\d+)$/);if(m){const fn=scenarios[Number(m[1])-1];if(!fn)return json({status:"ERROR",error:"UNKNOWN_SCENARIO"},404);const r=await fn(env);return json(r,r.status==="PASS"?200:503)}if(path==="/supergau/server-matrix"){const results=[];for(const fn of scenarios)results.push(await fn(env));const pass=results.every(x=>x.status==="PASS");return json({service:"KC Failover Gateway",test:"SERVER-SUPER-GAU-MATRIX",scenarioCount:results.length,status:pass?"PASS":"FAIL",results,timestamp:new Date().toISOString()},pass?200:503)}const p=await checkSupabase(env),f=await checkNeon(env),activeBackend=chooseBackend(p.reachable,f.reachable);return json({service:"KC Failover Gateway",status:activeBackend==="LOCAL_QUEUE"?"DEGRADED":"OK",activeBackend,primary:{name:"SUPABASE",...p},fallback:{name:"NEON",hyperdriveBinding:Boolean(env.HYPERDRIVE?.connectionString),...f},durablePosJournal:f.reachable,localQueueRequired:activeBackend==="LOCAL_QUEUE",timestamp:new Date().toISOString()})}catch(e){const message=e instanceof Error?e.message:"UNKNOWN_ERROR",status=message.startsWith("INVALID_")||message==="TRANSACTION_TOO_LARGE"?400:500;return json({status:"ERROR",error:message},status)}}};
